sudo: required
services: 
  - docker
before_install:
  - docker build -t Naman201995/docker-react-image -f Dockerfile.dev .
script: 
  - docker run -e CI=true Naman201995/docker-react-image npm run test